apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p2azb8grx-java-springboot
  janus-idp.io/tekton: p2azb8grx-java-springboot
  backstage.io/kubernetes-id: p2azb8grx-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p2azb8grx-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
